### PR TITLE
Added documentation

### PR DESCRIPTION
**Pull request by codingjoe**
This isn't quite done yet, but have a first look. I added loads documentation.

I found that you had flake8 as a dependency, but did not execute the command. I added it as well as pep257, for even better documentation.

### CODE REVIEW

**Comment by codingjoe** [comment]
@kmmbvnr I'm done for now. I didn't fix all documentation according to pep257 but a big portion.
I also refactored the tox config. Travis now tests on both python3.3 and 3.4.
It also executes flake8 and pep256, but it is allowed to fail.

I hope that helps. The documentation I added should certainly help many other people to get into viewflow.

**Comment by codingjoe** [comment]
@kmmbvnr any sign of life? I think this could be really helpful for some people.

**Comment by kmmbvnr** [comment]
That's to much changes from my point of view. I'll pick the new doc strings only.

Some of the changes breaks my workflow, ex: including additional commands to the default tox run, prevents running custom django commands for the shell (see postargs)

Too broad packages version specification, makes requirements.io notifications out of service, in case of new minor versions will come. And etc.

**Comment by codingjoe** [comment]
@kmmbvnr put the tox and travis changes in #101 
The PR only contains docs and some cleanup.

**Comment by kmmbvnr** [comment]
Great, Thank you!

**Pull request merged**
